x-common-configuration: &common
  restart: unless-stopped
  runtime: nvidia
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  volumes:
    - ./data:/app/data
  shm_size: '20gb'  # Common shared memory size for all services
  deploy:
    resources:
      limits:
        memory: 20G  # Common memory limit for all services

services:
  text_to_speech_service:
    <<: *common
    build:
      context: ./text_to_speech_docker
      dockerfile: Dockerfile
    image: text_to_speech_image:latest
    container_name: text_to_speech_container
    ports:
      - "8080:8080"

  deepfake_service:
    <<: *common
    build:
      context: ./deepfake_docker
      dockerfile: Dockerfile
    image: deepfake_image:latest
    container_name: deepfake_container
    ports:
      - "7000:8080"